source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
use_frameworks!

target 'sdk-bridge-sample' do
	pod 'XyBleSdk', '~> 3.0.1'
	pod 'sdk-objectmodel-swift', '~> 3.0'
    pod 'sdk-core-swift', '~> 3.0.1'
    pod 'sdk-xyobleinterface-swift', '~> 3.0.4'
    pod 'sdk-bletcpbridge-swift', :path => '../'
end
